name: adasubtraction
channels:
  - defaults
  - conda-forge
  - numba
dependencies:
  - python>=3.6.4
  - pip
  - numpy>=1.15.0
  - scipy>=1.4.0
  - pandas
  - matplotlib
  - ipython
  - jupyter
  - pylops==1.18.2
  - tqdm
  - pip:
    - segyio
