name: adasubtraction
channels:
  - defaults
  - conda-forge
  - numba
dependencies:
  - python>=3.9.0
  - numpy==1.23.1
  - scipy>=1.4.0
  - pylops==1.18.3
  - pip
  - cupy
  - matplotlib
  - ipython
  - qtpy
  - jupyter
  - tqdm
  - pip:
    - setuptools_scm
    - kymatio 
    - devito>=4.7.1
    - torch>=2.0.1 
    - segyio
  
